   services:
     - type: web
       name: Voting App
       env: node
       buildCommand: npm ci && npm rebuild bcrypt --build-from-source
       startCommand: node server.js
       envVars:
         - key: NODE_ENV
           value: production
         - key: MONGO_URL
           sync: false