   services:
     - type: web
       name: Voting App
       env: node       
       buildCommand: npm ci
       startCommand: node server.js
       envVars:
         - key: NODE_ENV
           value: production
         - key: MONGO_URL
           sync: false